name: Generate Snake

on:
  schedule: 
    - cron: "0 0 * * *"  # executa todo dia à meia-noite
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
      - name: Gerar animação da cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: alecksander-sena
          outputs: dist/snake.svg
      - name: Publicar no branch output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
